#! /bin/sh


xrdb ~/.xrdb
xmodmap ~/.Xmodmap

xterm &
xterm &
xterm &

while true; do
  xsetroot -name `date "+%H:%M"`
  sleep 60
done &

tabbed -d -f -n browser surf -e > /home/pk/.tabbed.xid
emacs &

exec dwm
